#joint_names: ["arm_1_joint","arm_2_joint","arm_3_joint","arm_4_joint","arm_5_joint","arm_6_joint","arm_7_joint"]

# back side positions
home: [[0,0,0,0,0,0,0]]
calib: [[-0.08223, -1.88519, 0.57768, -0.59635, 0.24536, 1.37332, -1.40385]]

